name: CI and CD
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    uses: Lucky3028/shared-workflows/.github/workflows/scala-ci.yml@main
    with:
      cache-build-deps-ver: v-1
      cache-build-outputs-ver: v-1
      jar-output-dir: target/scala-2.13
  cd:
    uses: Lucky3028/shared-workflows/.github/workflows/scala-cd.yml@main
    if: github.ref == 'refs/heads/main'
    needs:
      - ci
