name: CI and CD
on:
  push:
    paths:
      - src/**
      - build.sbt
      - .scalafix.conf
      - .scalafmt.conf
      - project/*
      - .github/**
  pull_request:
    paths:
      - src/**
      - build.sbt
      - .scalafix.conf
      - .scalafmt.conf
      - project/*
      - .github/**

jobs:
  ci:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Prepare build dependencies cache
        uses: actions/cache@v3
        env:
          cache-name: cache-build-dependencies
          cache-version: v-1
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.m2
            ~/.cache
          key: build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-
            build-${{ env.cache-name }}-${{ env.cache-version }}-
      - name: Prepare build cache
        if: github.ref != 'refs/heads/main'
        uses: actions/cache@v3
        env:
          cache-name: cache-build
          cache-version: v-1
        with:
          path: |
            target
            project/target
            project/project/target
          key: build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            build-${{ env.cache-name }}-${{ env.cache-version }}-${{ github.ref }}-
            build-${{ env.cache-name }}-${{ env.cache-version }}-

      - name: Check format with Scalafmt
        run: sbt scalafmtCheckAll
      - name: Check lint with Scalafix
        run: sbt "scalafix --check"
      - name: Build artifact with Test
        run: sbt assembly

      - name: Clean build artifact for caching target folder
        run: rm -r target/build
